# Docker run settings for redis-adapter.
# Author: Vasiliy Zdanovskiy
# email: vasilyvz@gmail.com

CONTAINER_NAME=redis-adapter
IMAGE_NAME=redis-adapter
NETWORK_NAME=smart-assistant

REDIS_HOST_PORT=63790
